# do this when a new issue is created
on:
  issues:
    types: [opened]
name: ✏️ Add Abstract Pull Request

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  check-user-access:
    if: contains(github.event.issue.labels.*.name, 'abstract')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Get the github handle of the user and check it against the allowed_users.txt file
      - name: Get the user
        id: get_user
        run: echo "user=${{ github.event.issue.user.login }}" >> $GITHUB_OUTPUT
      - name: Check user access
        id: check_user
        run: |
          user=${{ steps.get_user.outputs.user }}
          if ! grep -q $user allowed_users.txt; then
            echo "User $user is not allowed to create abstracts"
            gh issue close ${{ github.event.issue.number }} --comment "Issue closed: User $user is not allowed to create abstracts"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-abstract:
    needs: check-user-access
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # TODO: Replace with OIDC
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.MONDRIANMUSE_AZURE_CREDENTIALS }}
    # Escape double quotes in the issue body and set it as an environment variable
    - name: ⛓️‍💥 Escape double quotes
      run: |
        echo "ESCAPED_ISSUE_BODY<<EOF" >> $GITHUB_ENV
        echo "${{ github.event.issue.body }}" | sed 's/"/\\"/g' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: ✨ Create a pull request
      id: create_pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        ESCAPED_ISSUE_BODY: ${{ env.ESCAPED_ISSUE_BODY }}
      run: | 
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        python pr-abstracts/create-pull-request.py --answers "$ESCAPED_ISSUE_BODY" | tee output.log
        FILE=$(grep "^FILE=" output.log | cut -d'=' -f2)
        PR_URL=$(grep "^PR_URL=" output.log | cut -d'=' -f2)
        PR_ID=$(echo $PR_URL | cut -d'/' -f7)
        echo "file_path=$FILE" >> $GITHUB_OUTPUT
        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        echo "pr_id=$PR_ID" >> $GITHUB_OUTPUT
    - name: 💬 Update the issue
      run: |
        gh issue comment $ISSUE --body "✅ Created pull request: ${{ steps.create_pr.outputs.pr_url }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}
    - name: 🔍 Review the abstract
      env:
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        ESCAPED_ISSUE_BODY: ${{ env.ESCAPED_ISSUE_BODY }}
        FILE_PATH: ${{ steps.create_pr.outputs.file_path }}
      run: | 
        python issue-based-abstracts/review-abstract_promptflow.py --answers "$ESCAPED_ISSUE_BODY" --abstract "$(cat FILE_PATH)" > review.txt
    - run: gh pr comment $PR_ID --body "$(cat review.txt)"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_ID: ${{ steps.create_pr.outputs.pr_id }}
